global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'hospital-metrics'
    static_configs:
      - targets: ['main_host:8000']  # or wherever your metrics come from
